//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonaEditor.ApplicationSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class AppSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSetting defaultInstance = ((AppSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSetting())));
        
        public static AppSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P4")]
        public string BMDFontDefault {
            get {
                return ((string)(this["BMDFontDefault"]));
            }
            set {
                this["BMDFontDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P4")]
        public string PTPOldDefault {
            get {
                return ((string)(this["PTPOldDefault"]));
            }
            set {
                this["PTPOldDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P4_RUS")]
        public string PTPNewDefault {
            get {
                return ((string)(this["PTPNewDefault"]));
            }
            set {
                this["PTPNewDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string PTPBackgroundDefault {
            get {
                return ((string)(this["PTPBackgroundDefault"]));
            }
            set {
                this["PTPBackgroundDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("font")]
        public string DirFont {
            get {
                return ((string)(this["DirFont"]));
            }
            set {
                this["DirFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("background")]
        public string DirBackground {
            get {
                return ((string)(this["DirBackground"]));
            }
            set {
                this["DirBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P4")]
        public string BMDFontDestDefault {
            get {
                return ((string)(this["BMDFontDestDefault"]));
            }
            set {
                this["BMDFontDestDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string DefaultLocalization {
            get {
                return ((string)(this["DefaultLocalization"]));
            }
            set {
                this["DefaultLocalization"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00000000")]
        public global::System.Windows.Media.Color PreviewSelectedColor {
            get {
                return ((global::System.Windows.Media.Color)(this["PreviewSelectedColor"]));
            }
            set {
                this["PreviewSelectedColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveAsPTP_CO2N {
            get {
                return ((bool)(this["SaveAsPTP_CO2N"]));
            }
            set {
                this["SaveAsPTP_CO2N"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string SaveAsPTP_Font {
            get {
                return ((string)(this["SaveAsPTP_Font"]));
            }
            set {
                this["SaveAsPTP_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveAsPTP_NeverAskAgain {
            get {
                return ((bool)(this["SaveAsPTP_NeverAskAgain"]));
            }
            set {
                this["SaveAsPTP_NeverAskAgain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string OpenPTP_Font {
            get {
                return ((string)(this["OpenPTP_Font"]));
            }
            set {
                this["OpenPTP_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenPTP_NeverAskAgain {
            get {
                return ((bool)(this["OpenPTP_NeverAskAgain"]));
            }
            set {
                this["OpenPTP_NeverAskAgain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SingleInstanceApplication {
            get {
                return ((bool)(this["SingleInstanceApplication"]));
            }
            set {
                this["SingleInstanceApplication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PTPImageView {
            get {
                return ((bool)(this["PTPImageView"]));
            }
            set {
                this["PTPImageView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public global::System.Windows.GridLength PTPNameBlockSize {
            get {
                return ((global::System.Windows.GridLength)(this["PTPNameBlockSize"]));
            }
            set {
                this["PTPNameBlockSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string FTDEncoding {
            get {
                return ((string)(this["FTDEncoding"]));
            }
            set {
                this["FTDEncoding"] = value;
            }
        }
    }
}
