//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonaEditor.ApplicationSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class BackgroundDefault : global::System.Configuration.ApplicationSettingsBase {
        
        private static BackgroundDefault defaultInstance = ((BackgroundDefault)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BackgroundDefault())));
        
        public static BackgroundDefault Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double EmptyGlyphScale {
            get {
                return ((double)(this["EmptyGlyphScale"]));
            }
            set {
                this["EmptyGlyphScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int EmptyWidth {
            get {
                return ((int)(this["EmptyWidth"]));
            }
            set {
                this["EmptyWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int EmptyHeight {
            get {
                return ((int)(this["EmptyHeight"]));
            }
            set {
                this["EmptyHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF808080")]
        public global::System.Windows.Media.Color EmptyBackgroundColor {
            get {
                return ((global::System.Windows.Media.Color)(this["EmptyBackgroundColor"]));
            }
            set {
                this["EmptyBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color EmptyTextColor {
            get {
                return ((global::System.Windows.Media.Color)(this["EmptyTextColor"]));
            }
            set {
                this["EmptyTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color EmptyNameColor {
            get {
                return ((global::System.Windows.Media.Color)(this["EmptyNameColor"]));
            }
            set {
                this["EmptyNameColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EmptyLineSpacing {
            get {
                return ((int)(this["EmptyLineSpacing"]));
            }
            set {
                this["EmptyLineSpacing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70,50")]
        public global::System.Windows.Point EmptyTextPos {
            get {
                return ((global::System.Windows.Point)(this["EmptyTextPos"]));
            }
            set {
                this["EmptyTextPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0")]
        public global::System.Windows.Point EmptyNamePos {
            get {
                return ((global::System.Windows.Point)(this["EmptyNamePos"]));
            }
            set {
                this["EmptyNamePos"] = value;
            }
        }
    }
}
