//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonaEditor.ApplicationSettings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class WindowSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static WindowSetting defaultInstance = ((WindowSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new WindowSetting())));
        
        public static WindowSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public double MWWidth {
            get {
                return ((double)(this["MWWidth"]));
            }
            set {
                this["MWWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double MWHeight {
            get {
                return ((double)(this["MWHeight"]));
            }
            set {
                this["MWHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public global::System.Windows.GridLength MWLeftWidth {
            get {
                return ((global::System.Windows.GridLength)(this["MWLeftWidth"]));
            }
            set {
                this["MWLeftWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MWPropertyExpanded {
            get {
                return ((bool)(this["MWPropertyExpanded"]));
            }
            set {
                this["MWPropertyExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MWPosX {
            get {
                return ((double)(this["MWPosX"]));
            }
            set {
                this["MWPosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MWPosY {
            get {
                return ((double)(this["MWPosY"]));
            }
            set {
                this["MWPosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState MWState {
            get {
                return ((global::System.Windows.WindowState)(this["MWState"]));
            }
            set {
                this["MWState"] = value;
            }
        }
    }
}
