//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonaEditorGUI.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class BackgroundDefault : global::System.Configuration.ApplicationSettingsBase {
        
        private static BackgroundDefault defaultInstance = ((BackgroundDefault)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BackgroundDefault())));
        
        public static BackgroundDefault Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string SelectedBackground {
            get {
                return ((string)(this["SelectedBackground"]));
            }
            set {
                this["SelectedBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Empty")]
        public string SelectedBackgroundVisual {
            get {
                return ((string)(this["SelectedBackgroundVisual"]));
            }
            set {
                this["SelectedBackgroundVisual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double EmptyGlyphScale {
            get {
                return ((double)(this["EmptyGlyphScale"]));
            }
            set {
                this["EmptyGlyphScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public int EmptyWidth {
            get {
                return ((int)(this["EmptyWidth"]));
            }
            set {
                this["EmptyWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int EmptyHeight {
            get {
                return ((int)(this["EmptyHeight"]));
            }
            set {
                this["EmptyHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color EmptyBackgroundColor {
            get {
                return ((global::System.Windows.Media.Color)(this["EmptyBackgroundColor"]));
            }
            set {
                this["EmptyBackgroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int EmptyTextX {
            get {
                return ((int)(this["EmptyTextX"]));
            }
            set {
                this["EmptyTextX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int EmptyTextY {
            get {
                return ((int)(this["EmptyTextY"]));
            }
            set {
                this["EmptyTextY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color EmptyTextColor {
            get {
                return ((global::System.Windows.Media.Color)(this["EmptyTextColor"]));
            }
            set {
                this["EmptyTextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EmptyNameX {
            get {
                return ((int)(this["EmptyNameX"]));
            }
            set {
                this["EmptyNameX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EmptyNameY {
            get {
                return ((int)(this["EmptyNameY"]));
            }
            set {
                this["EmptyNameY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color EmptyNameColor {
            get {
                return ((global::System.Windows.Media.Color)(this["EmptyNameColor"]));
            }
            set {
                this["EmptyNameColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EmptyLineSpacing {
            get {
                return ((int)(this["EmptyLineSpacing"]));
            }
            set {
                this["EmptyLineSpacing"] = value;
            }
        }
    }
}
